#pragma once

#include "Core/Platform.h"
#include "Core/Common.h"
#include "Core/Version.hpp"
#include "Core/SystemConsole.h"

#include "Types/Array.hpp"
#include "Types/Text.h"
#include "Types/Vector2.hpp"
#include "Types/Vector3.hpp"
#include "Types/Matrix2.hpp"
#include "Types/Matrix3.hpp"
#include "Types/Matrix4.hpp"
#include "Types/Rect2.hpp"
#include "Types/Transform.h"
#include "Types/Color.hpp"
#include "Types/MeshPrimitives.hpp"
#include "Types/Mesh.h"
#include "Types/Multisamples.h"
#include "Types/RenderCoordinateSpace.hpp"

#include "Interface/Instance.h"
#include "Interface/Window.h"
#include "Interface/RenderTargetTexture.h"
#include "Interface/Sampler.h"
#include "Interface/Texture.h"

#include "Interface/ResourceManager/ResourceManager.h"
#include "Interface/ResourceManager/Resource.h"
#include "Interface/ResourceManager/TextureResource.h"
#include "Interface/ResourceManager/FontResource.h"
